name: bms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ESPHome Firmware
        uses: esphome/build-action@main
        with:
          yaml-file: esp32-ble-example.yaml

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: jk-bms-firmware-bin
          path: |
            .esphome/build/jk-bms/.pioenvs/jk-bms/firmware.bin
